import './js/libs/weapp-adapter'
import './js/libs/symbol'
import './js/libs/lodash';
import './pixi.js';
import './js/src/phaser.js';
import './js/src/geom.js';
import './js/src/pixidefs.js';
import './js/src/core.js';
import './js/src/system.js';
import './js/src/utils.js';
import './js/src/animation.js';
import './js/src/physics.js';
import './js/src/arcade.js';
import './js/src/bitmapdata.js';
import './js/src/components.js';
import './js/src/bitmaptext.js';
import './js/src/color.js';
import './js/src/create.js';
import './js/src/creature.js';
import './js/src/debug.js';
import './js/src/dom.js';
import './js/src/flexgrid.js';
import './js/src/input.js';
import './js/src/gameobjects.js';
import './js/src/gamepad.js';
import './js/src/loader.js';
import './js/src/math.js';
import './js/src/net.js';
import './js/src/particles.js';
import './js/src/rope.js';
import './js/src/scale.js';
import './js/src/sound.js';
import './js/src/text.js';
import './js/src/tilesprite.js';
import './js/src/time.js';
import './js/src/tweens.js';
import './js/src/graphics.js';
import initgame from './Parkour/InitGame/initGame.js'
new initgame();